CREATE TABLE Accounts (
    AccountID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    AccountHolderName VARCHAR2(100),
    AccountType VARCHAR2(20),
    Balance NUMBER(10, 2)
);

INSERT INTO Accounts (AccountHolderName, AccountType, Balance) VALUES
('Ankit', 'Savings', 1000.00);

INSERT INTO Accounts (AccountHolderName, AccountType, Balance) VALUES
('Aman', 'Savings', 2000.00);

INSERT INTO Accounts (AccountHolderName, AccountType, Balance) VALUES
('Virat', 'Checking', 1500.00);

INSERT INTO Accounts (AccountHolderName, AccountType, Balance) VALUES
('Dhoni', 'Savings', 3000.00);

CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    EmployeeName VARCHAR2(100),
    DepartmentID NUMBER,
    Salary NUMBER(10, 2)
);

INSERT INTO Employees (EmployeeName, DepartmentID, Salary) VALUES
('Jay', 1, 5000.00);

INSERT INTO Employees (EmployeeName, DepartmentID, Salary) VALUES
('Hardik', 1, 5500.00);

INSERT INTO Employees (EmployeeName, DepartmentID, Salary) VALUES
('Jadeja', 2, 6000.00);

INSERT INTO Employees (EmployeeName, DepartmentID, Salary) VALUES
('Kuldeep', 2, 5800.00);

--1

CREATE PROCEDURE ProcessMonthlyInterest IS
BEGIN
    UPDATE Accounts
    SET Balance = Balance * 1.01
    WHERE AccountType = 'Savings';
END;
/

--2

CREATE PROCEDURE UpdateEmployeeBonus (
    p_DepartmentID IN NUMBER,
    p_BonusPercent IN NUMBER
) IS
BEGIN
    UPDATE Employees
    SET Salary = Salary + (Salary * p_BonusPercent / 100)
    WHERE DepartmentID = p_DepartmentID;
END;
/

--3

CREATE OR REPLACE PROCEDURE TransferFunds (
    p_FromAccountID IN NUMBER,
    p_ToAccountID IN NUMBER,
    p_Amount IN NUMBER
) IS
    v_FromBalance NUMBER;
BEGIN

    SELECT Balance INTO v_FromBalance
    FROM Accounts
    WHERE AccountID = p_FromAccountID;

    IF v_FromBalance < p_Amount THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient funds in source account.');
    END IF;

    UPDATE Accounts
    SET Balance = Balance - p_Amount
    WHERE AccountID = p_FromAccountID;

    UPDATE Accounts
    SET Balance = Balance + p_Amount
    WHERE AccountID = p_ToAccountID;
END;
/


EXEC ProcessMonthlyInterest;

Select * from accounts;

EXEC UpdateEmployeeBonus(1, 10);

SELECT * from EMPLOYEES;

EXEC TransferFunds(1, 3, 500);

SELECT * From ACCOUNTS;